FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

# install general packages
RUN apt-get update && apt-get install -y --no-install-recommends curl gnupg ca-certificates
RUN curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB | apt-key add -
RUN echo "deb [trusted=yes] https://apt.repos.intel.com/oneapi all main " > /etc/apt/sources.list.d/oneAPI.list
RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ make
RUN apt-get update && apt-get install -y --no-install-recommends intel-oneapi-compiler-fortran

# ENV TBBROOT="/opt/intel/oneapi/tbb/2021.5.1/env/.."
ENV ONEAPI_ROOT="/opt/intel/oneapi"
ENV PKG_CONFIG_PATH="/opt/intel/oneapi/mpi/2021.7.0/lib/pkgconfig:/opt/intel/oneapi/compiler/2022.2.0/lib/pkgconfig"
ENV I_MPI_ROOT="/opt/intel/oneapi/mpi/2021.7.0"
# ENV FPGA_VARS_DIR="/opt/intel/oneapi/compiler/2022.0.2/linux/lib/oclfpga"
# ENV DPL_ROOT="/opt/intel/oneapi/dpl/2021.6.0"
ENV MANPATH="/opt/intel/oneapi/mpi/2021.7.0/man:/opt/intel/oneapi/debugger/2021.7.0/documentation/man:/opt/intel/oneapi/compiler/2022.2.0/documentation/en/man/common::"
ENV DIAGUTIL_PATH="/opt/intel/oneapi/debugger/2021.7.0/sys_check/debugger_sys_check.py:/opt/intel/oneapi/compiler/2022.2.0/sys_check/sys_check.sh"

ENV FI_PROVIDER_PATH="/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov:/usr/lib64/libfabric"
ENV GDB_INFO="/opt/intel/oneapi/debugger/2021.7.0/documentation/info/"
ENV CMAKE_PREFIX_PATH="/opt/intel/oneapi/compiler/2022.2.0/linux/IntelDPCPP"
ENV CMPLR_ROOT="/opt/intel/oneapi/compiler/2022.2.0"
ENV INFOPATH="/opt/intel/oneapi/debugger/2021.7.0/gdb/intel64/lib"
ENV LIBRARY_PATH="/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib:/opt/intel/oneapi/mpi/2021.7.0//lib/release:/opt/intel/oneapi/mpi/2021.7.0//lib:/opt/intel/oneapi/compiler/2022.2.0/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/compiler/2022.2.0/linux/lib"
ENV OCL_ICD_FILENAMES="/opt/intel/oneapi/compiler/2022.2.0/linux/lib/x64/libintelocl.so"
ENV INTELFPGAOCLSDKROOT="/opt/intel/oneapi/compiler/2022.0.2/linux/lib/oclfpga"
ENV LD_LIBRARY_PATH="/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib:/opt/intel/oneapi/mpi/2021.7.0//lib/release:/opt/intel/oneapi/mpi/2021.7.0//lib:/opt/intel/oneapi/debugger/2021.7.0/gdb/intel64/lib:/opt/intel/oneapi/debugger/2021.7.0/libipt/intel64/lib:/opt/intel/oneapi/debugger/2021.7.0/dep/lib:/opt/intel/oneapi/compiler/2022.2.0/linux/lib:/opt/intel/oneapi/compiler/2022.2.0/linux/lib/x64:/opt/intel/oneapi/compiler/2022.2.0/linux/compiler/lib/intel64_lin"
ENV NLSPATH="/opt/intel/oneapi/compiler/2022.2.0/linux/compiler/lib/intel64_lin/locale/%l_%t/%N"
ENV PATH="/opt/intel/oneapi/mpi/2021.7.0//libfabric/bin:/opt/intel/oneapi/mpi/2021.7.0//bin:/opt/intel/oneapi/debugger/2021.7.0/gdb/intel64/bin:/opt/intel/oneapi/compiler/2022.2.0/linux/bin/intel64:/opt/intel/oneapi/compiler/2022.2.0/linux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV INTEL_PYTHONHOME="/opt/intel/oneapi/debugger/2021.7.0/dep"
ENV CPATH="/opt/intel/oneapi/mpi/2021.7.0//include"
ENV CLASSPATH="/opt/intel/oneapi/mpi/2021.7.0//lib/mpi.jar"

CMD [ "bash" ]
